#!/bin/sh

set -o errexit

sudo apt-get install vim ack-grep ctags build-essential cmake python-dev git

mkdir -p ~/tmp
rm -rf ~/tmp/vim-backup
mkdir -p ~/.vim
mv ~/.vim ~/tmp/vim-backup

git clone https://github.com/weekface/vimfile.git ~/.vim

rm ~/.vimrc
rm ~/.gvimrc

ln -s ~/.vim/.vimrc ~/.vimrc
ln -s ~/.vim/.gvimrc ~/.gvimrc

touch ~/.vim/.vimrc_local
touch ~/.vim/.gvimrc_local

mkdir -p ~/.vim/vundle
cd ~/.vim/vundle && git clone git://github.com/gmarik/vundle.git .
vim +BundleInstall +qall
vim +GoInstallBinaries +qall
