#!/bin/sh

sudo apt-get install vim vim-gtk ack-grep git

rm -Rf ~/.vim
rm ~/.vimrc

mkdir -p ~/.vim/autoload ~/.vim/bundle && \
	curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
	https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim 

cp ./vimrc ~/.vimrc
cp ./gvimrc ~/.gvimrc
